### ISSUE TITLE
windows_386 version v0.2.2

### ISSUE THREAD

**Issue by smudge1977** [elsudano/terraform-provider-vmworkstation#10]
Hi

I am trying to run on a windows machine - do i need to install GO and compile this?
Going to here `https://registry.terraform.io/elsudano/vmworkstation` gives a 404 anyway?
Sorry this is my fir terraform testing so maybe user error!!!

Thanks

```
terraform {
  required_version = ">= 0.15.4"
  required_providers {
    vmworkstation = {

      source  = "registry.terraform.io/elsudano/vmworkstation"
      version = "0.2.2"
    }
  }
}
```

```
Initializing provider plugins...
- Finding elsudano/vmworkstation versions matching "0.2.2"...
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/elsudano/vmworkstation v0.2.2 does not have a package available for your current
│ platform, windows_386.
```

**Comment by elsudano** [comment]
Sorry for the delay in my answer, fortunately you can use the latest version to solve this issue

https://registry.terraform.io/providers/elsudano/vmworkstation/latest

All the feedback will be welcome
