### ISSUE TITLE
Still creating. help??

### ISSUE THREAD

**Issue by strechty** [elsudano/terraform-provider-vmworkstation#16]
Vmware Workstation 17 pro 
provider version 1.1.6 
OS: debian 12 

main.tf 
  GNU nano 7.2                                     main.tf                                               
terraform {
  required_providers {
    vmworkstation = {
      source = "elsudano/vmworkstation"
      version = "1.1.6"
    }
  }
}

provider "vmworkstation" {
        user = "strecht"
        password = "qey8mTq*GNgV"
        url = "http://127.0.0.1:8697"
        https = false
        debug = false
}
resource "vmworkstation_vm" "test_machine" {
  sourceid     = "8PVELF46LPB24A514G493QOGS03N103G"
  denomination = "TF-Test"
  description  = ""
  path         = "/home/strecht/Downloads/TF-Test.vmx"
  processors   = "4"
  memory       = "4096"
}

But when applied it shows
strecht@strecht:~/terraform/projecttest$ sudo terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vmworkstation_vm.test_machine will be created
  + resource "vmworkstation_vm" "test_machine" {
      + denomination = "TF-Test"
      + id           = (known after apply)
      + ip           = (known after apply)
      + memory       = 4096
      + path         = "/home/strecht/Downloads/TF-Test.vmx"
      + processors   = 4
      + sourceid     = "8PVELF46LPB24A514G493QOGS03N103G"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vmworkstation_vm.test_machine: Creating...
vmworkstation_vm.test_machine: Still creating... [10s elapsed]
vmworkstation_vm.test_machine: Still creating... [20s elapsed]
vmworkstation_vm.test_machine: Still creating... [30s elapsed]
vmworkstation_vm.test_machine: Still creating... [40s elapsed]
vmworkstation_vm.test_machine: Still creating... [50s elapsed]
vmworkstation_vm.test_machine: Still creating... [1m0s elapsed]
vmworkstation_vm.test_machine: Still creating... [1m10s elapsed]
vmworkstation_vm.test_machine: Still creating... [1m20s elapsed]
vmworkstation_vm.test_machine: Still creating... [1m30s elapsed]
vmworkstation_vm.test_machine: Still creating... [1m40s elapsed]
vmworkstation_vm.test_machine: Still creating... [1m50s elapsed]
vmworkstation_vm.test_machine: Still creating... [2m0s elapsed]
vmworkstation_vm.test_machine: Still creating... [2m10s elapsed]
vmworkstation_vm.test_machine: Still creating... [2m20s elapsed]
vmworkstation_vm.test_machine: Still creating... [2m30s elapsed]
vmworkstation_vm.test_machine: Still creating... [2m40s elapsed]
vmworkstation_vm.test_machine: Still creating... [2m50s elapsed]
vmworkstation_vm.test_machine: Still creating... [3m0s elapsed]
vmworkstation_vm.test_machine: Still creating... [3m10s elapsed]

and doesn't create the vm

**Comment by elsudano** [comment]
Hi, thanks to try our provider

In order to see the issue better, could you put DEBUG mode on true?

provider "vmworkstation" {
user = "strecht"
password = "qey8mTq*GNgV"
url = "http://127.0.0.1:8697/"
https = false
**debug = true**
}

Send me the results when you run again the apply

Regards

**Comment by strechty** [comment]
[ERROR][WSAPICLI] Fi: wsapivm.go Fu: CreateVM Obj:Request Error &json.UnmarshalTypeError{Value:"number", Type:(*reflect.rtype)(0xfed620), Offset:3, Struct:"", Field:""}
  | [ERROR][VMWS] Fi: resource_vmworkstation_vm.go Fu: resourceVMWSVmCreate Error Creating VM: &json.UnmarshalTypeError{Value:"number", Type:(*reflect.rtype)(0xfed620), Offset:3, Struct:"", Field:""}
ok i think this is the problem but i dont know what it means

**Comment by strechty** [comment]
i think is because of space but i have 600 gb free in the path i specified

**Comment by elsudano** [comment]
Are you sure that the Path of the VM os correcta?

I mean, you need put the path where VmWare Workstation have configure the default folder of the VMs

**Comment by strechty** [comment]
its the same path were the other vm is

**Comment by strechty** [comment]
[
  {
    "id": "8PVELF46LPB24A514G493QOGS03N103G",
    "path": "/home/strecht/Downloads/Ubuntu-22.04-Build/jammy-2022-04-17.vmx"
  }
]

**Comment by strechty** [comment]
and when i try to use the api directly this error appears 
{
  "Code": 3,
  "Message": "Internal server error: An error occurred while cloning: There is not enough space on the file system for the selected operation.\n"
}

**Comment by elsudano** [comment]
For that reason I told you that you need to check the configuration of the VmWare Workstation.

Because I think that you have created all your machines in download folder, but the default folder of the VMware Workstation seems to be another different.

Could you try to create a instance directly from the browser by the API call?

Maybe there you can see more details

**Comment by strechty** [comment]
form the api call the response is this 
![errorrapi](https://github.com/elsudano/terraform-provider-vmworkstation/assets/120052606/f2da00e0-5cab-41e2-ad6c-3861aa4d9580)

**Comment by strechty** [comment]
i my bad on the picture i have 2 monitors

**Comment by strechty** [comment]
thanks for the feed back iam going to try to solve this and sorry for wasting your time

**Comment by elsudano** [comment]
So, then something happend with your configuration of VMware, because you need to create a test VM before to try with the provider.

**Comment by elsudano** [comment]
Ok, I will close the issue, isn't related with the provider, for the moment ;-)

**Comment by strechty** [comment]
amazing its working now
