### ISSUE TITLE
Source id field

### ISSUE THREAD

**Issue by alby97** [elsudano/terraform-provider-vmworkstation#4]
Hi, I want to use this provider that is really interesting but I didn't understand what is this required "source_id" and where I should look for it. Probably this is a naive question but I didn't find anything about that.

**Comment by elsudano** [comment]
Hi alby,

If you want understand the source_id parameter the better way is read about of the API REST to VmWare Workstation.

If you want, you can take a look at the repo https://github.com/elsudano/vmware-workstation-api-client

The previous repo is a client of API REST to VmWare Workstation, in this repo you can read taht the source_id is a required parameter of the API REST, for that is necessary that the provider storage this value of the VMs.

Also you can will view that client is used in the provider, really is the base of communication between provider and API REST.

I hope that explanation is enough for you.

Please if you use this provider, let me know you feedback

Cheers

**Comment by alby97** [comment]
Hi, thanks for your reply, I've tried your client and also to interact with the server without your client but it always returns an empy response. In my VMWare Workstation I've two VM that I built with Packer so I suppose that this could be the problem, because in some way the system didn't register them completely or something like that. Do this have ever happened to you with or without VM built with Packer?

**Comment by elsudano** [comment]
Hi, Alby

I don't know if I'm understanding you correctly, but according to what you explains, the workaround you is doing is that you  creating the VMs with packer so that from VmWare Workstation you can run them. Is that so?

Firstly here, you use the API REST of the VmWare Workstation? you can test follow this link https://localhost:8697/api?

You can test different methods in this link when you active the api rest of VmWare Workstation.

Let me know if this is enough for you

Greeats

**Comment by alby97** [comment]
Hi, yes this is what I'm trying to do.
I've tried to list all the virtual networks and that works but for the others API is required the id as you said in your first reply and because that specific API returns an empty response (with status code 200) I can't test them. 
However, thanks for the reply.

**Comment by elsudano** [comment]
Hi,

Yep, for me is exactly same situation but for other method of the API.

In my case, the method is for get a one parameter of the VM, when I asking for the value, the API response me with a 404 status and I don't know why?

Please let me know if you learn some workaround  about this.

Thanks in advance
