### ISSUE TITLE
Fine-grained read module support

### ISSUE THREAD

**Issue by banna2019** [elsudano/terraform-provider-vmworkstation#9]
Can there be updated and fine-grained module support? For example, select the network of the local VMware Workstation, select the system type of the new virtual machine of the local VMware Workstation, select the image in the specified local path, and set some configurations in the system? Like setting static IP address, turn off firewall

**Comment by elsudano** [comment]
Sorry for the delay, yep, we want to improve the provider in this way, but for the moment we want to create a destroy resources ans also, update VM's when the support team of the VmWare Workstation solve the issue with the API call about of the configparams

https://developer.vmware.com/apis/413/

This link have the old version of the API
